## Write a program to obtain shift matrix P with input.

In [3]:
import numpy as np
def shift_matrix(m,N):
    P = np.zeros((m,m),dtype=int)
    k = 0
    elem = N%m
    while k<m:
        P[k][elem] = 1
        elem=(elem+1)%m
        k+=1
    return P


print(f'Shift Matrix:')
P = shift_matrix(4,1)
print(P)

Shift Matrix:
[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [1 0 0 0]]


## Circulant Matrix

In [4]:
def circulant_matrix(N,C):
    C_N = np.zeros((N,N),dtype=int)
    for i in range(N):
        C_N[i] = np.roll(C,i)

    return C_N

C_N = circulant_matrix(4,[2,-1,0,-1])
print('Circulant Matrix: \n',C_N)

Circulant Matrix: 
 [[ 2 -1  0 -1]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [-1  0 -1  2]]


## Eigenvectors of P_N & C_N



In [47]:
def eigen_P_C(P,C):
    eig_val_P, eig_vect_P = np.linalg.eig(P)
    eig_val_C, eig_vect_C = np.linalg.eig(C)
    print('Eigenvalue of P_N:', eig_val_P)
    print('\nEigenvector of P_N:', eig_vect_P)
    print('\nEigenvalue of C_N:', eig_val_C)
    print('\nEigenvector of C_N:', eig_vect_P)

    
    norm_eig_vect_C = np.linalg.norm(eig_vect_C)
    norm_eig_vect_P = np.linalg.norm(eig_vect_P)
    print(f'\nNorm of Eig Vect C: {norm_eig_vect_C}')
    print(f'Norm of Eig Vect P: {norm_eig_vect_P}')
eigen_P_C(P,C_N)

Eigenvalue of P_N: [-1.00000000e+00+0.j  8.32667268e-17+1.j  8.32667268e-17-1.j
  1.00000000e+00+0.j]

Eigenvector of P_N: [[ 5.00000000e-01+0.00000000e+00j  2.63941871e-16-5.00000000e-01j
   2.63941871e-16+5.00000000e-01j  5.00000000e-01+0.00000000e+00j]
 [-5.00000000e-01+0.00000000e+00j  5.00000000e-01-1.34144886e-16j
   5.00000000e-01+1.34144886e-16j  5.00000000e-01+0.00000000e+00j]
 [ 5.00000000e-01+0.00000000e+00j -2.85804968e-18+5.00000000e-01j
  -2.85804968e-18-5.00000000e-01j  5.00000000e-01+0.00000000e+00j]
 [-5.00000000e-01+0.00000000e+00j -5.00000000e-01+0.00000000e+00j
  -5.00000000e-01-0.00000000e+00j  5.00000000e-01+0.00000000e+00j]]

Eigenvalue of C_N: [-4.4408921e-16  4.0000000e+00  2.0000000e+00  2.0000000e+00]

Eigenvector of C_N: [[ 5.00000000e-01+0.00000000e+00j  2.63941871e-16-5.00000000e-01j
   2.63941871e-16+5.00000000e-01j  5.00000000e-01+0.00000000e+00j]
 [-5.00000000e-01+0.00000000e+00j  5.00000000e-01-1.34144886e-16j
   5.00000000e-01+1.34144886e-16j  5.00000

In [35]:
def fourier_matrix(n):
    F = np.zeros((n,n), dtype = complex)
    omega = np.exp((-2j*np.pi)/n)
    for i in range(n):
        for j in range(n):
            if i == 0 or j == 0:
                F[i,j] = 1
            else:
                F[i,j] = omega**(i*j)
    return F

F = fourier_matrix(4)
print('Fourier Matrix:\n',F)

eig_F, eig_val_F = np.linalg.eig(F)
print('\nEigenvalue of F:', eig_val_F)
print('\nEigenvector of F:', eig_F)


Fourier Matrix:
 [[ 1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j
   1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17-1.0000000e+00j
  -1.0000000e+00-1.2246468e-16j -1.8369702e-16+1.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j -1.0000000e+00-1.2246468e-16j
   1.0000000e+00+2.4492936e-16j -1.0000000e+00-3.6739404e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16+1.0000000e+00j
  -1.0000000e+00-3.6739404e-16j  5.5109106e-16-1.0000000e+00j]]

Eigenvalue of F: [[ 8.66025404e-01+0.00000000e+00j -5.00000000e-01+3.42424236e-17j
   4.60192388e-17-3.71041199e-17j -2.29279012e-02+7.95271299e-03j]
 [ 2.88675135e-01-1.97698725e-17j  5.00000000e-01+0.00000000e+00j
   7.07106781e-01+0.00000000e+00j -4.15728453e-01+3.97635649e-03j]
 [ 2.88675135e-01-1.97698725e-17j  5.00000000e-01+0.00000000e+00j
  -4.97620772e-17-1.92358536e-16j  8.08529004e-01+0.00000000e+00j]
 [ 2.88675135e-01-1.97698725e-17j  5.00000000e-01+0.00000000e+00j

In [41]:
def fourier_norm(F):
    F_trans = F.transpose()
    norms = np.zeros(len(F),dtype=int)
    for i in range(len(norms)):
        norms[i] = np.linalg.norm(F_trans[i])
    print(f'Norm of Fourier: {norms}')
    print(f'Transpose of Fourier:\n {F_trans}\n')
    return norms,F_trans

def normalised_F(trans_F,norms):
    normalised_F = np.zeros((len(norms),len(norms)),dtype=complex)
    for i in range(len(norms)):
        normalised_F[i] = trans_F[i]/norms[i]
    return normalised_F.transpose()
    

norms,trans_F = fourier_norm(F)
normalised_F = normalised_F(trans_F, norms)

print(f'Normalised F:\n {normalised_F}')

Norm of Fourier: [2 2 2 2]
Transpose of Fourier:
 [[ 1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j
   1.0000000e+00+0.0000000e+00j  1.0000000e+00+0.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j  6.1232340e-17-1.0000000e+00j
  -1.0000000e+00-1.2246468e-16j -1.8369702e-16+1.0000000e+00j]
 [ 1.0000000e+00+0.0000000e+00j -1.0000000e+00-1.2246468e-16j
   1.0000000e+00+2.4492936e-16j -1.0000000e+00-3.6739404e-16j]
 [ 1.0000000e+00+0.0000000e+00j -1.8369702e-16+1.0000000e+00j
  -1.0000000e+00-3.6739404e-16j  5.5109106e-16-1.0000000e+00j]]

Normalised F:
 [[ 5.00000000e-01+0.0000000e+00j  5.00000000e-01+0.0000000e+00j
   5.00000000e-01+0.0000000e+00j  5.00000000e-01+0.0000000e+00j]
 [ 5.00000000e-01+0.0000000e+00j  3.06161700e-17-5.0000000e-01j
  -5.00000000e-01-6.1232340e-17j -9.18485099e-17+5.0000000e-01j]
 [ 5.00000000e-01+0.0000000e+00j -5.00000000e-01-6.1232340e-17j
   5.00000000e-01+1.2246468e-16j -5.00000000e-01-1.8369702e-16j]
 [ 5.00000000e-01+0.0000000e+00j -9.18485099e-

## Convolution Rule

In [51]:
import numpy as np
from scipy.fft import fft, ifft

# Define two discrete functions (arrays)
c = np.array([1, 2, 3, 4])
d = np.array([0, 1, 0, 0])

# Compute the convolution of c and d
convolution = np.convolve(c, d)

# Compute the Fourier transform of c and d
F_c = fft(c)
F_d = fft(d)

# Compute the product of Fourier transforms
product_of_ft = F_c * F_d

# Compute the inverse Fourier transform of the product
inverse_ft = ifft(product_of_ft)

print("Convolution:", convolution)
print("Inverse Fourier Transform of the product:", inverse_ft)


Convolution: [0 1 2 3 4 0 0]
Inverse Fourier Transform of the product: [4.+0.j 1.+0.j 2.+0.j 3.-0.j]
